import type { Metadata } from "next";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import theme from "../Theme/themeConfig";

import "../globals.css";
import { ConfigProvider } from "antd";
import Navbar from "./components/Navbar";
import Footer from "./components/ui/Footer";
import { AuthProvider } from "@/context/AuthContext";
import {
  faFacebook,
  faInstagram,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = [{ key: "1", label: "CATALOG", href: "/catalog" }];
  const info = {
    address: "156 E 2nd St, New York, NY 10009, United States",
    email: "info@chair.com",
    phone: "+6600088888",
    socialLinks: [
      { icon: faFacebook, href: "https://facebook.com" },
      { icon: faInstagram, href: "https://instagram.com" },
      { icon: faYoutube, href: "https://youtube.com" },
    ],
  };
  return (
    <ConfigProvider theme={theme}>
      <AntdRegistry>
        <Navbar menuItems={menuItems} />
        <AuthProvider>{children}</AuthProvider>

        <Footer menuItems={menuItems} info={info}></Footer>
      </AntdRegistry>
    </ConfigProvider>
  );
}
