import type { Metadata } from "next";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import theme from "../Theme/themeConfig";

import "../globals.css";
import { ConfigProvider } from "antd";
import Navbar from "./components/Navbar";
import Footer from "./components/ui/Footer";
import { AuthProvider } from "@/context/AuthContext";
import {
  faFacebook,
  faInstagram,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = [{ key: "1", label: "CATALOG", href: "/catalog" }];
  const info = {
    address:
      "19 Tanthong Rd., Fah-ham Sub-District, Muang District, Chiang main 50000",
    email: "cschonlapat@gmail.com",
    phone: "094-838-6636",
    socialLinks: [
      { icon: faFacebook, href: "https://facebook.com" },
      { icon: faInstagram, href: "https://instagram.com" },
      { icon: faYoutube, href: "https://youtube.com" },
    ],
  };
  return (
    <ConfigProvider theme={theme}>
      <AntdRegistry>
        <Navbar menuItems={menuItems} />
        <div className="pt-20 px-4 sm:px-6 lg:px-8">
          <AuthProvider>{children}</AuthProvider>
        </div>

        <Footer menuItems={menuItems} info={info}></Footer>
      </AntdRegistry>
    </ConfigProvider>
  );
}
